/* Interactive renal physiology and diagnostic reasoning tools. */
(() => {
  "use strict";
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const safe = window.RenalLabUI.escapeHTML;

  const segmentData = {
    glomerulus:{title:"Glomerulus",subtitle:"Filtration unit",transport:"Filters water and small solutes while retaining blood cells and most large proteins.",permeability:"Selectivity depends on endothelium, basement membrane, podocyte slit diaphragms, molecule size/shape, protein binding, and barrier integrity.",control:"Afferent and efferent arteriolar tone, autoregulation, mesangial surface area, and systemic hemodynamics determine pressure and Kf.",drug:"NSAIDs can reduce afferent vasodilation; RAAS blockers reduce efferent tone. Effects depend on volume and clinical context.",failure:"Albuminuria, dysmorphic RBCs, RBC casts, reduced GFR, edema, hypertension, or nephritic/nephrotic syndromes."},
    proximal:{title:"Proximal tubule",subtitle:"Bulk recovery and secretion",transport:"Reabsorbs most filtered sodium and water, most bicarbonate, nearly all normal glucose and amino acids, plus phosphate and other solutes; secretes organic acids and bases.",permeability:"High water permeability keeps tubular fluid approximately iso-osmotic during bulk reabsorption.",control:"Angiotensin II and sympathetic tone promote sodium recovery; PTH reduces phosphate reabsorption.",drug:"Carbonic anhydrase inhibitors reduce bicarbonate reabsorption; SGLT2 inhibitors reduce glucose and sodium reabsorption.",failure:"Fanconi pattern, glycosuria without hyperglycemia, bicarbonate loss, phosphate wasting, aminoaciduria, and low-molecular-weight proteinuria."},
    descending:{title:"Thin descending limb",subtitle:"Water-extracting limb",transport:"Allows water to leave as the tubule descends into the hypertonic medulla, concentrating tubular fluid.",permeability:"High water permeability with relatively limited salt transport.",control:"Depends on the medullary osmotic gradient generated by countercurrent multiplication and preserved by vasa recta.",drug:"No major routine diuretic target is emphasized here; loop diuretics indirectly reduce its concentrating effect by collapsing the medullary gradient.",failure:"Reduced concentrating ability when the medullary gradient is lost or tubular flow is abnormal."},
    tal:{title:"Thick ascending limb",subtitle:"Salt reabsorption without water",transport:"Reabsorbs sodium, potassium, and chloride through NKCC2; lumen-positive voltage supports calcium and magnesium handling.",permeability:"Effectively impermeable to water, so it dilutes tubular fluid and builds the medullary gradient.",control:"Transport depends on NKCC2 and potassium recycling; tubuloglomerular signaling senses downstream NaCl delivery.",drug:"Loop diuretics block NKCC2, increase salt delivery distally, reduce the medullary gradient, and can increase calcium/magnesium losses.",failure:"Salt wasting, hypokalemic metabolic alkalosis, impaired concentration, and Bartter-like physiology."},
    dct:{title:"Distal convoluted tubule",subtitle:"Fine salt and calcium control",transport:"Reabsorbs sodium chloride through NCC; distal calcium handling is influenced by PTH.",permeability:"Low water permeability in the early distal tubule contributes to dilution.",control:"PTH promotes calcium reabsorption; distal salt delivery affects downstream potassium and acid handling.",drug:"Thiazide diuretics block NCC and tend to reduce urinary calcium excretion.",failure:"Gitelman-like physiology: salt wasting, hypokalemic metabolic alkalosis, hypomagnesemia, and low urinary calcium."},
    collecting:{title:"Collecting duct",subtitle:"Final regulated urine",transport:"Principal cells reabsorb sodium through ENaC, secrete potassium, and regulate water via aquaporin-2. Intercalated cells handle H+ or bicarbonate.",permeability:"Water permeability varies greatly with ADH; without ADH, dilute urine can be excreted.",control:"Aldosterone increases ENaC and potassium/H+ secretion; ADH controls water permeability; distal sodium delivery and flow strongly affect potassium secretion.",drug:"ENaC blockers and mineralocorticoid antagonists are potassium-sparing; vasopressin antagonists reduce ADH-mediated water reabsorption.",failure:"Hyperkalemia or hypokalemia, distal renal tubular acidosis, nephrogenic diabetes insipidus, or inappropriate water retention depending on the defect."}
  };

  function initNephron(){
    const root = $("#nephron-tool"); if(!root) return;
    const buttons = $$('[data-segment]',root), out = $("#nephron-output",root);
    const render = id => {
      const d = segmentData[id] || segmentData.glomerulus;
      buttons.forEach(b=>{const active=b.dataset.segment===id;b.classList.toggle("active",active);b.setAttribute("aria-selected",String(active));b.tabIndex=active?0:-1;});
      out.innerHTML = `<span class="badge">${safe(d.subtitle)}</span><h3>${safe(d.title)}</h3><div class="lab-detail-grid"><div><strong>Core transport</strong><p>${safe(d.transport)}</p></div><div><strong>Water/permeability</strong><p>${safe(d.permeability)}</p></div><div><strong>Physiological control</strong><p>${safe(d.control)}</p></div><div><strong>Drug connection</strong><p>${safe(d.drug)}</p></div></div><div class="callout warning"><h3>Failure pattern</h3><p>${safe(d.failure)}</p></div>`;
    };
    buttons.forEach((b,index)=>{
      b.setAttribute("role","tab");
      b.addEventListener("click",()=>render(b.dataset.segment));
      b.addEventListener("keydown",e=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;e.preventDefault();let next=index;if(e.key==="ArrowLeft")next=(index-1+buttons.length)%buttons.length;if(e.key==="ArrowRight")next=(index+1)%buttons.length;if(e.key==="Home")next=0;if(e.key==="End")next=buttons.length-1;buttons[next].focus();render(buttons[next].dataset.segment);});
    });
    render("glomerulus");
  }

  function initFiltration(){
    const root=$("#filtration-tool"); if(!root)return;
    const out=$("#filtration-output",root), ids=["#f-pgc","#f-pbs","#f-onc","#f-kf"];
    const n=id=>Number($(id,root)?.value||0);
    const render=()=>{
      const pgc=n("#f-pgc"),pbs=n("#f-pbs"),onc=n("#f-onc"),kf=n("#f-kf");
      const nfp=pgc-pbs-onc, relative=Math.max(0,nfp*kf), baseline=10, pct=Math.max(0,Math.min(100,relative/baseline*50));
      let title,tone,explain;
      if(nfp<=0){title="No net filtration in this simplified model";tone="danger";explain="Opposing pressures equal or exceed glomerular hydrostatic pressure. Severe obstruction, very low glomerular pressure, or very high oncotic opposition can move physiology in this direction.";}
      else if(relative<5){title="Markedly reduced filtration drive";tone="warning";explain="Net pressure or Kf is low. Ask whether perfusion, obstruction, barrier surface area, or severe hemodynamic disturbance is responsible.";}
      else if(relative>18){title="High filtration drive";tone="purple";explain="Higher pressure or Kf raises filtration in the model. Chronic intraglomerular hypertension can be maladaptive even when GFR appears preserved or high.";}
      else{title="Moderate positive filtration drive";tone="success";explain="The forces produce a positive NFP. Real GFR also depends on changing oncotic pressure along the capillary, nephron number, and autoregulation.";}
      out.innerHTML=`<div class="callout ${tone}"><h3>${title}</h3><p>${explain}</p></div><div class="formula-result"><span>Net filtration pressure</span><strong>${nfp.toFixed(1)} mmHg</strong><small>${pgc.toFixed(1)} − ${pbs.toFixed(1)} − ${onc.toFixed(1)}</small></div><div class="formula-result"><span>Relative filtration index (Kf × NFP)</span><strong>${relative.toFixed(1)}</strong><small>Conceptual, not mL/min</small></div><div class="result-meter" aria-label="Relative filtration indicator"><span style="width:${pct}%"></span></div>`;
    };
    ids.forEach(id=>$(id,root)?.addEventListener("input",render)); render();
  }

  function initCrCl(){
    const root=$("#crcl-tool"); if(!root)return;
    const out=$("#crcl-output",root), ids=["#cg-age","#cg-weight","#cg-creatinine","#cg-sex"];
    const n=id=>Number($(id,root)?.value||0);
    const render=()=>{
      const age=n("#cg-age"),wt=n("#cg-weight"),scr=n("#cg-creatinine"),sex=n("#cg-sex");
      if(age<=0||wt<=0||scr<=0){out.innerHTML='<div class="callout danger"><h3>Enter valid positive values</h3></div>';return;}
      const crcl=((140-age)*wt)/(72*scr)*sex;
      let band=crcl>=90?"≥90":crcl>=60?"60-89":crcl>=30?"30-59":crcl>=15?"15-29":"<15";
      out.innerHTML=`<div class="formula-result"><span>Estimated Cockcroft-Gault creatinine clearance</span><strong>${Math.max(0,crcl).toFixed(1)} mL/min</strong><small>Approximate band: ${band} mL/min</small></div><p><strong>Substitution:</strong> [(140 − ${age}) × ${wt} kg] / [72 × ${scr} mg/dL] × ${sex.toFixed(2)}</p><div class="callout warning"><h3>Interpretation limits</h3><p>This is not eGFR and is not indexed to 1.73 m². Weight selection, muscle mass, age, edema/obesity, amputation, diet, drugs, and changing kidney function can make it misleading. Use the medicine-specific dosing instruction.</p></div>`;
    };
    ids.forEach(id=>$(id,root)?.addEventListener("input",render)); render();
  }

  function initUrine(){
    const root=$("#urine-tool"); if(!root)return;
    const ids=["#u-blood","#u-rbc","#u-morph","#u-protein","#u-wbc","#u-clue"], out=$("#urine-output",root);
    const v=id=>$(id,root)?.value;
    const render=()=>{
      const blood=v("#u-blood"),rbc=v("#u-rbc"),morph=v("#u-morph"),protein=v("#u-protein"),wbc=v("#u-wbc"),clue=v("#u-clue");
      const findings=[]; let title="Nonspecific or low-signal pattern",tone="info", action="Repeat a properly collected fresh specimen and interpret with kidney function, symptoms, and trend.";
      if(blood==="positive"&&rbc==="none"){
        if(clue==="muscle"){title="Myoglobinuria pattern";tone="danger";findings.push("Heme-positive dipstick without RBCs plus muscle injury suggests rhabdomyolysis.");action="Check CK, potassium, creatinine, calcium, acid-base status, and urine output urgently.";}
        else if(clue==="hemolysis"){title="Hemoglobinuria pattern";tone="danger";findings.push("Heme-positive dipstick without RBCs plus hemolysis clues suggests intravascular hemolysis.");action="Evaluate CBC, smear, LDH, haptoglobin, bilirubin, plasma color, and cause.";}
        else{title="Heme pigment or lysed-RBC pattern";tone="warning";findings.push("Dipstick blood is positive but intact RBCs are absent.");action="Repeat a fresh sample and assess for hemolysis, rhabdomyolysis, dilute/alkaline urine, or contamination.";}
      }
      if(morph==="rbccast"||morph==="dysmorphic"){
        title="Glomerular bleeding pattern";tone=clue==="pulmonary"?"danger":"warning";findings.push(morph==="rbccast"?"RBC casts strongly localize bleeding to glomeruli.":"Dysmorphic RBCs/acanthocytes support a glomerular source.");
        if(protein!=="none")findings.push("Accompanying albumin/protein strengthens a renal parenchymal pattern.");
        action=clue==="pulmonary"?"Urgent pulmonary-renal syndrome assessment with nephrology/critical care.":"Assess creatinine/eGFR, BP, UACR/PCR, complements and targeted serology; refer according to severity.";
      } else if(morph==="clots"){
        title="Non-glomerular/urologic bleeding pattern";tone="warning";findings.push("Clots strongly favor bleeding from the urinary tract rather than glomerular capillaries.");action="Assess retention and stability, then use symptom- and malignancy-risk-based urologic evaluation.";
      } else if(rbc!=="none"&&protein==="heavy"){
        title="Renal parenchymal disease possible";tone="warning";findings.push("Hematuria with heavy protein is not typical of uncomplicated lower-tract bleeding.");action="Quantify albumin, inspect morphology/casts, assess kidney function and nephrology urgency while retaining urologic evaluation if risk remains.";
      }
      if(wbc==="wbccast"){
        title="Renal inflammatory / upper-tract pattern";tone=clue==="flank"?"danger":"warning";findings.push("WBC casts localize inflammation to renal tubules/interstitium.");action=clue==="flank"?"Culture, treat pyelonephritis promptly, and assess obstruction/sepsis.":"Consider pyelonephritis or interstitial nephritis using culture, drugs, symptoms, and imaging.";
      } else if(wbc==="lower"&&clue==="dysuria"){
        title="Lower urinary infection/inflammation pattern";tone="success";findings.push("Pyuria/infection markers plus dysuria support cystitis or urethritis.");action="Culture when indicated, treat appropriately, and repeat urinalysis if hematuria was present.";
      }
      if(clue==="colic"&&rbc!=="none"&&morph!=="rbccast"&&morph!=="dysmorphic"){
        title="Stone/obstruction pattern";tone="warning";findings.push("Colicky pain with non-glomerular hematuria is compatible with urolithiasis.");action="Assess analgesia, infection, kidney function, solitary kidney/anuria, and image appropriately.";
      }
      if(!findings.length)findings.push("No single high-specificity combination is selected. A bland or minimal result can still be important when kidney function is changing.");
      out.innerHTML=`<div class="callout ${tone}"><h3>${title}</h3><ul class="clean-list">${findings.map(x=>`<li>${safe(x)}</li>`).join("")}</ul></div><h3>Next-step framework</h3><p>${safe(action)}</p><p class="muted small">This tool recognizes patterns; it does not diagnose an individual patient.</p>`;
    };
    ids.forEach(id=>$(id,root)?.addEventListener("change",render));render();
  }

  function initProtein(){
    const root=$("#protein-tool");if(!root)return;
    const ids=["#p-acr","#p-pcr","#p-albumin","#p-edema","#p-dip","#p-sediment"],out=$("#protein-output",root);
    const n=id=>Number($(id,root)?.value||0),v=id=>$(id,root)?.value;
    const render=()=>{
      const acr=n("#p-acr"),pcr=n("#p-pcr"),albumin=n("#p-albumin"),edema=v("#p-edema"),dip=v("#p-dip"),sed=v("#p-sediment");
      const aCat=acr<30?"A1: normal to mildly increased":acr<=300?"A2: moderately increased":"A3: severely increased";
      const pCat=pcr<0.15?"Within a typical total-protein reference range":pcr<0.5?"Low-grade proteinuria":pcr<3.5?"Subnephrotic proteinuria":"Nephrotic-range proteinuria";
      const nephrotic=pcr>=3.5&&albumin<3&&edema==="yes";
      const nonAlbumin=pcr>=0.5&&acr<Math.min(300,pcr*100)&&dip==="negative";
      const points=[];
      if(nephrotic)points.push("Heavy total protein, hypoalbuminemia, and edema form a nephrotic syndrome pattern.");
      else if(pcr>=3.5)points.push("Total protein is nephrotic range, but full nephrotic syndrome requires systemic consequences such as hypoalbuminemia and edema.");
      if(nonAlbumin)points.push("High total protein with relatively little albumin and a weak dipstick suggests non-albumin/overflow protein.");
      if(sed==="rbc")points.push("Dysmorphic RBCs or RBC casts indicate active glomerular inflammation and increase urgency.");
      if(sed==="wbc")points.push("WBC casts or tubular cells suggest tubulointerstitial or upper-tract renal inflammation.");
      if(sed==="blood")points.push("Visible blood or infection can add post-renal protein; repeat after resolution to assess persistence.");
      if(!points.length)points.push("The pattern is best interpreted with persistence, blood pressure, eGFR, diabetes/systemic features, and sample quality.");
      let tone=nephrotic||sed==="rbc"?"danger":nonAlbumin||acr>300||pcr>=3.5?"warning":"success";
      out.innerHTML=`<div class="section-grid"><div class="mini-card stat-card"><strong>${safe(aCat.split(":")[0])}</strong><span>${safe(aCat.split(": ")[1]||aCat)}</span></div><div class="mini-card stat-card"><strong>${pcr.toFixed(2)} g/g</strong><span>${safe(pCat)}</span></div></div><div class="callout ${tone}"><h3>Integrated interpretation</h3><ul class="clean-list">${points.map(x=>`<li>${safe(x)}</li>`).join("")}</ul></div><p><strong>Next:</strong> Confirm persistence with a first-morning sample, quantify ACR and PCR appropriately, inspect sediment, assess serum albumin/eGFR/BP, and order targeted secondary-cause or paraprotein testing.</p>`;
    };
    ids.forEach(id=>$(id,root)?.addEventListener("input",render));ids.forEach(id=>$(id,root)?.addEventListener("change",render));render();
  }

  function initSources(){
    const root=$("#source-tool");if(!root)return;
    const select=$("#pdf-select",root),frame=$("#pdf-frame",root),open=$("#pdf-open",root);
    const render=()=>{const value=select.value;open.href=value;frame.data=value;};
    select.addEventListener("change",render);render();
  }

  function initRoute(route){
    if(route==="nephron-lab")initNephron();
    if(route==="filtration-lab")initFiltration();
    if(route==="crcl-lab")initCrCl();
    if(route==="urine-interpreter")initUrine();
    if(route==="proteinuria-lab")initProtein();
    if(route==="sources")initSources();
  }
  window.RenalLabLabs={initRoute};
})();
