/* TTS, cases, flashcards, quiz, and personal study notes. */
(() => {
  "use strict";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const data=window.RenalLabData, safe=window.RenalLabUI.escapeHTML;
  const store={get(k,f=null){try{const v=localStorage.getItem(k);return v===null?f:v}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
  const parse=(k,f)=>{try{return JSON.parse(store.get(k,"null"))??f}catch{return f}};

  const speech={button:null,unit:null,chunks:[],index:0,paused:false,session:0,utterance:null};
  function splitSpeech(text){const out=[];let rest=text.replace(/\s+/g," ").trim();while(rest){if(rest.length<=720){out.push(rest);break}let cut=Math.max(rest.lastIndexOf(". ",720),rest.lastIndexOf("; ",720),rest.lastIndexOf(", ",720),rest.lastIndexOf(" ",720));if(cut<250)cut=720;out.push(rest.slice(0,cut+1).trim());rest=rest.slice(cut+1).trim()}return out}
  function preferredVoice(){const voices=speechSynthesis.getVoices();return voices.find(v=>/Google UK English Female/i.test(v.name))||voices.find(v=>/^en-GB$/i.test(v.lang)&&/female|sonia|serena|libby|susan|hazel/i.test(v.name))||voices.find(v=>/^en-GB$/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||voices[0]}
  function speechText(unit){const clone=unit.cloneNode(true);clone.querySelectorAll(".block-tools,.listen-button,button,input,select,textarea,object,script,style,[hidden],.interactive-only").forEach(n=>n.remove());return(clone.textContent||"").replace(/\s+/g," ").trim()}
  function setSpeechLabel(button,state){if(!button)return;button.classList.toggle("is-speaking",state==="playing");button.dataset.speechState=state;button.textContent=state==="playing"?"❚❚ Pause":state==="paused"?"▶ Continue":"▶ Listen";button.setAttribute("aria-label",state==="playing"?"Pause reading this section":state==="paused"?"Continue reading this section":"Listen to this section")}
  function resetSpeech(){speech.session++;try{speechSynthesis.cancel()}catch{}setSpeechLabel(speech.button,"idle");Object.assign(speech,{button:null,unit:null,chunks:[],index:0,paused:false,utterance:null})}
  function speakNext(){if(speech.index>=speech.chunks.length){setSpeechLabel(speech.button,"idle");Object.assign(speech,{button:null,unit:null,chunks:[],index:0,paused:false,utterance:null});return}const session=speech.session;const u=new SpeechSynthesisUtterance(speech.chunks[speech.index]);const voice=preferredVoice();if(voice)u.voice=voice;u.lang=voice?.lang||"en-GB";u.rate=Number($("#speech-rate")?.value)||.92;u.onend=()=>{if(session!==speech.session||speech.paused)return;speech.index++;speakNext()};u.onerror=e=>{if(session!==speech.session||["interrupted","canceled"].includes(e.error))return;speech.paused=true;setSpeechLabel(speech.button,"paused")};speech.utterance=u;speech.paused=false;setSpeechLabel(speech.button,"playing");speechSynthesis.speak(u)}
  function toggleSpeech(button){if(!("speechSynthesis" in window))return;const unit=button.closest(".speech-unit");if(!unit)return;
    if(speech.button===button){
      if(speech.paused||speechSynthesis.paused){try{speechSynthesis.resume()}catch{}speech.paused=false;setSpeechLabel(button,"playing");return}
      if(speechSynthesis.speaking){try{speechSynthesis.pause()}catch{}speech.paused=true;setSpeechLabel(button,"paused");return}
      if(speech.index<speech.chunks.length){speech.paused=false;speakNext();return}
    }
    resetSpeech();const chunks=splitSpeech(speechText(unit));if(!chunks.length)return;speech.session++;speech.button=button;speech.unit=unit;speech.chunks=chunks;speech.index=0;speech.paused=false;speakNext();
  }
  function enhanceSpeech(root=document){if(!("speechSynthesis" in window))return;$$('.speech-unit',root).forEach((unit,i)=>{if(unit.querySelector(":scope > .block-tools"))return;const heading=unit.querySelector(":scope > .section-heading");if(heading){const tools=document.createElement("div");tools.className="block-tools interactive-only";tools.innerHTML='<button class="listen-button" type="button" aria-label="Listen to this section">▶ Listen</button>';heading.appendChild(tools)}else if(unit.matches(".mini-card,.callout")){const b=document.createElement("button");b.className="listen-button interactive-only";b.type="button";b.setAttribute("aria-label","Listen to this item");b.textContent="▶ Listen";b.style.marginTop=".6rem";unit.appendChild(b)}})}

  let caseIndex=0;
  function initCases(){const list=$("#case-list"),card=$("#case-card");if(!list||!card)return;const render=()=>{list.innerHTML=data.cases.map((c,i)=>`<button class="${i===caseIndex?"active":""}" type="button" data-case-index="${i}"><strong>${i+1}. ${safe(c.title)}</strong><span class="small" style="display:block;opacity:.76">${safe(c.tag)}</span></button>`).join("");const c=data.cases[caseIndex];card.innerHTML=`<span class="badge">${safe(c.tag)}</span><h3>${safe(c.title)}</h3><p>${safe(c.stem)}</p><div class="clue-grid">${c.clues.map(x=>`<div class="clue">${safe(x)}</div>`).join("")}</div><div class="callout purple"><h3>Your task</h3><p>${safe(c.question)}</p></div><details class="reveal"><summary>1. Reveal diagnosis</summary><div><strong>${safe(c.diagnosis)}</strong></div></details><details class="reveal"><summary>2. Reveal reasoning</summary><div>${safe(c.reasoning)}</div></details><details class="reveal"><summary>3. Reveal next-step framework</summary><div>${safe(c.action)}</div></details><details class="reveal"><summary>4. Exam pearl</summary><div>${safe(c.pearl)}</div></details>`;enhanceSpeech(card)};list.addEventListener("click",e=>{const b=e.target.closest("[data-case-index]");if(!b)return;caseIndex=Number(b.dataset.caseIndex);render()});render()}

  const flashState={all:data.flashcards,filtered:[],index:0,flipped:false,category:"All",known:new Set(parse("renal-flash-known",[])),again:new Set(parse("renal-flash-again",[]))};
  const cardKey=c=>`${c.tag}|${c.q}`;
  function saveFlash(){store.set("renal-flash-known",JSON.stringify([...flashState.known]));store.set("renal-flash-again",JSON.stringify([...flashState.again]))}
  function initFlashcards(){const root=$("#flashcard-app");if(!root)return;const select=$("#flash-category",root);select.innerHTML=["All",...new Set(flashState.all.map(c=>c.tag))].map(x=>`<option>${safe(x)}</option>`).join("");select.value=flashState.category;select.addEventListener("change",()=>{flashState.category=select.value;filterFlash()});$("#flash-shuffle",root).addEventListener("click",()=>{flashState.filtered.sort(()=>Math.random()-.5);flashState.index=0;flashState.flipped=false;renderFlash()});$("#flash-reset",root).addEventListener("click",()=>{flashState.known.clear();flashState.again.clear();saveFlash();renderFlash()});filterFlash()}
  function filterFlash(){flashState.filtered=flashState.category==="All"?[...flashState.all]:flashState.all.filter(c=>c.tag===flashState.category);flashState.index=0;flashState.flipped=false;renderFlash()}
  function renderFlash(){const stage=$("#flash-stage");if(!stage)return;const cards=flashState.filtered;if(!cards.length){stage.innerHTML="<p>No cards in this category.</p>";return}flashState.index=(flashState.index+cards.length)%cards.length;const c=cards[flashState.index],key=cardKey(c);stage.innerHTML=`<button class="flash-card ${flashState.flipped?"flipped":""}" id="active-flash-card" type="button" aria-pressed="${flashState.flipped}"><span class="flash-inner"><span class="flash-face flash-front"><span class="flash-tag">${safe(c.tag)}</span><strong>${safe(c.q)}</strong><small>Click or press Enter/Space to reveal the answer</small></span><span class="flash-face flash-back"><span class="flash-tag">Model answer</span><strong>${safe(c.a)}</strong><small>Click again to return to the question</small></span></span></button><div class="flash-nav"><button class="secondary-button" id="flash-prev" type="button">← Previous</button><div class="flash-rating"><button class="secondary-button danger-button" data-flash-rate="again" type="button">↺ Review again</button><button class="primary-button" data-flash-rate="known" type="button">✓ Know it</button></div><button class="secondary-button" id="flash-next" type="button">Next →</button></div>`;
    const flip=()=>{flashState.flipped=!flashState.flipped;const b=$("#active-flash-card");b.classList.toggle("flipped",flashState.flipped);b.setAttribute("aria-pressed",String(flashState.flipped))};$("#active-flash-card").addEventListener("click",flip);$("#flash-prev").addEventListener("click",()=>moveFlash(-1));$("#flash-next").addEventListener("click",()=>moveFlash(1));$$('[data-flash-rate]',stage).forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();if(b.dataset.flashRate==="known"){flashState.known.add(key);flashState.again.delete(key)}else{flashState.again.add(key);flashState.known.delete(key)}saveFlash();moveFlash(1)}));$("#flash-count").textContent=`Card ${flashState.index+1} of ${cards.length} · ${flashState.all.length} total`;$("#flash-stats").textContent=`${flashState.known.size} known · ${flashState.again.size} marked for review`}
  function moveFlash(delta){flashState.index=(flashState.index+delta+flashState.filtered.length)%flashState.filtered.length;flashState.flipped=false;renderFlash()}

  const initialQuiz={index:0,score:0,answered:false,selected:null,finished:false};let quizState=Object.assign({},initialQuiz,parse("renal-quiz-state",initialQuiz));
  function saveQuiz(){store.set("renal-quiz-state",JSON.stringify(quizState))}
  function initQuiz(){const root=$("#quiz-app");if(!root)return;$("#quiz-restart",root).addEventListener("click",()=>{quizState={...initialQuiz};saveQuiz();renderQuiz()});renderQuiz()}
  function renderQuiz(){const stage=$("#quiz-stage"),progress=$("#quiz-progress"),meter=$("#quiz-meter");if(!stage)return;const total=data.quiz.length;
    if(quizState.finished||quizState.index>=total){quizState.finished=true;saveQuiz();const pct=Math.round(quizState.score/total*100);progress.textContent=`Completed · ${quizState.score}/${total}`;meter.style.width="100%";stage.innerHTML=`<div class="quiz-card"><span class="score-badge">${pct}%</span><h3>Quiz complete</h3><p>You answered <strong>${quizState.score}</strong> of <strong>${total}</strong> correctly.</p><p>${pct>=85?"Strong performance. Revisit cards marked for review and the integrated renal reasoning cases.":pct>=65?"Good base. Review the explanation for every missed item, then repeat the quiz.":"Return to the renal foundations, investigation pathways, and pattern-recognition pages before another attempt."}</p><button class="primary-button" id="quiz-finish-restart" type="button">Restart from question 1</button></div>`;$("#quiz-finish-restart").addEventListener("click",()=>{quizState={...initialQuiz};saveQuiz();renderQuiz()});return}
    const item=data.quiz[quizState.index];progress.textContent=`Question ${quizState.index+1} of ${total} · Score ${quizState.score}`;meter.style.width=`${quizState.index/total*100}%`;stage.innerHTML=`<article class="quiz-card"><span class="badge">Single best answer</span><h3>${safe(item.q)}</h3><div class="option-list">${item.options.map((o,i)=>`<button class="quiz-option ${quizState.answered?(i===item.answer?"correct":i===quizState.selected?"incorrect":""):""}" type="button" data-quiz-option="${i}" ${quizState.answered?"disabled":""}><span>${String.fromCharCode(65+i)}</span><span>${safe(o)}</span></button>`).join("")}</div>${quizState.answered?`<div class="quiz-feedback"><strong>${quizState.selected===item.answer?"Correct.":"Not quite."}</strong><p>${safe(item.explanation)}</p><button class="primary-button" id="quiz-next" type="button">${quizState.index===total-1?"Finish quiz":"Next question →"}</button></div>`:""}</article>`;
    if(!quizState.answered)$$('[data-quiz-option]',stage).forEach(b=>b.addEventListener("click",()=>{quizState.selected=Number(b.dataset.quizOption);quizState.answered=true;if(quizState.selected===item.answer)quizState.score++;saveQuiz();renderQuiz()}));else $("#quiz-next").addEventListener("click",()=>{quizState.index++;quizState.answered=false;quizState.selected=null;if(quizState.index>=total)quizState.finished=true;saveQuiz();renderQuiz()})
  }

  function setupNotes(){const dialog=$("#notes-dialog"),open=$("#notes-button"),close=$("#close-notes"),area=$("#study-notes"),status=$("#notes-status");if(!dialog||!open)return;area.value=store.get("renal-study-notes","");let timer;open.addEventListener("click",()=>dialog.showModal?dialog.showModal():dialog.setAttribute("open",""));close.addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});area.addEventListener("input",()=>{clearTimeout(timer);status.textContent="Saving…";timer=setTimeout(()=>{store.set("renal-study-notes",area.value);status.textContent="Saved locally"},250)});$("#clear-notes").addEventListener("click",()=>{area.value="";store.set("renal-study-notes","");status.textContent="Notes cleared"})}
  function bindGlobal(){
    setupNotes();
    document.addEventListener("click",e=>{const b=e.target.closest(".listen-button,#stop-speech");if(!b)return;e.preventDefault();e.stopPropagation();if(b.id==="stop-speech")resetSpeech();else toggleSpeech(b)},true);
    document.addEventListener("keydown",e=>{if((e.key===" "||e.key==="Enter")&&document.activeElement?.id==="active-flash-card"){e.preventDefault();document.activeElement.click()}});
  }
  function initRoute(route){resetSpeech();enhanceSpeech($("#app-content"));if(route==="clinical-cases")initCases();if(route==="flashcards")initFlashcards();if(route==="quiz")initQuiz()}
  window.RenalLabStudy={bindGlobal,initRoute,enhanceSpeech,resetSpeech};
})();
